---
- name: Check extra_vars.yaml exists
  ansible.builtin.stat:
    path: "{{ ansible_facts.user_dir }}/.local/etc/extra_vars.yaml"
  register: extra_vars_stat

- name: Deploy ansible-pull LaunchAgent
  ansible.builtin.template:
    src: com.kukv.mac-setup.plist.j2
    dest: "{{ ansible_facts.user_dir }}/Library/LaunchAgents/com.kukv.mac-setup.plist"
    mode: "0644"
  notify: Reload ansible-pull LaunchAgent
