---
- name: Tap third-party Homebrew repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - cirruslabs/cli

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew.formulae }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew.casks }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
